import type { BagCandidate } from './types';

export const bagCandidates: BagCandidate[] = [
  {
    id: 'small-nylon-crescent',
    name: 'Small Nylon Crescent Bag',
    family: 'nylon-crescent',
    imageUrl:
      'https://cdn.shopify.com/s/files/1/0851/3262/files/193e3d4f086038d4c07b4834e5fad7fee80166a7-2048x2560_10640691-af91-491a-b2c8-5df58bff7a49.jpg?v=1784245001',
    imageAlt: 'Small Nylon Crescent Bag in Black',
    bestFor: 'Light daily carry and going out',
    capacitySummary: 'Small capacity for essentials',
    carryStyle: 'Hands-free crossbody or shoulder carry',
    organizationSummary: 'Simple everyday organization',
    price: '$48',
    variantSummary: 'Multiple colors and prints',
    capacities: ['small'],
    carryModes: ['crossbody', 'shoulder'],
    useCases: ['daily', 'evening'],
    structures: ['soft'],
    priorities: ['compact', 'handsFree'],
    flexibilityScore: 7,
    tradeoffs: ['Best for lighter carry; not intended for laptop or bulky items.'],
  },
  {
    id: 'medium-nylon-crescent',
    name: 'Medium Nylon Crescent Bag',
    family: 'nylon-crescent',
    imageUrl:
      'https://cdn.shopify.com/s/files/1/0851/3262/files/ec2b079b66be49732ead22194d04b4d6ccc6946d-2048x2560_773f9ec1-dbf5-404c-b882-a5385b938eb0.jpg?v=1784311790',
    imageAlt: 'Medium Nylon Crescent Bag in Black',
    bestFor: 'Flexible everyday carry',
    capacitySummary: 'Medium capacity for daily items',
    carryStyle: 'Hands-free crossbody or shoulder carry',
    organizationSummary: 'Casual organization for daily essentials',
    price: '$56',
    variantSummary: 'Multiple colors and prints',
    capacities: ['medium'],
    carryModes: ['crossbody', 'shoulder'],
    useCases: ['daily', 'commute', 'evening'],
    structures: ['soft'],
    priorities: ['handsFree', 'versatile', 'giftable'],
    flexibilityScore: 10,
    tradeoffs: ['More flexible than compact options, but not the highest-capacity bag.'],
  },
  {
    id: 'large-nylon-crescent',
    name: 'Large Nylon Crescent Bag',
    family: 'nylon-crescent',
    imageUrl:
      'https://cdn.shopify.com/s/files/1/0851/3262/files/8fb50103d000e89cadbcea324e9296bcc3183e40-2048x2560_5107c7ce-b3f4-4836-838d-1bf1b34cd041.jpg?format=webp&height=1000&quality=85&v=1761332955&width=800',
    imageAlt: 'Large Nylon Crescent Bag in Black',
    bestFor: 'Hands-free carry with extra room',
    capacitySummary: 'Large capacity for daily extras',
    carryStyle: 'Hands-free crossbody or shoulder carry',
    organizationSummary: 'Roomy main compartment',
    price: '$68',
    variantSummary: 'Multiple colors and prints',
    capacities: ['large'],
    carryModes: ['crossbody', 'shoulder'],
    useCases: ['daily', 'commute', 'travel'],
    structures: ['soft'],
    priorities: ['capacity', 'handsFree'],
    flexibilityScore: 8,
    tradeoffs: ['Larger profile than an essentials bag.'],
  },
  {
    id: 'standard-baggu',
    name: 'Standard Baggu',
    family: 'reusable-bag',
    imageUrl:
      'https://cdn.shopify.com/s/files/1/0851/3262/files/2aa5b00e949a03976f331566e92642b35d78b4af-2048x2560.jpg?v=1784245088',
    imageAlt: 'Standard Baggu in Black',
    bestFor: 'Shopping, errands, and packable backup carry',
    capacitySummary: 'Large reusable capacity',
    carryStyle: 'Handheld or packed inside another bag',
    organizationSummary: 'Unstructured open carry',
    price: '$14',
    variantSummary: 'Multiple colors and prints',
    capacities: ['large'],
    carryModes: ['handheld', 'packable'],
    useCases: ['shopping', 'daily'],
    structures: ['soft'],
    priorities: ['capacity', 'giftable', 'versatile'],
    flexibilityScore: 9,
    tradeoffs: ['Great for hauling extras, but not hands-free or structured.'],
  },
  {
    id: 'horizontal-zip-duck-bag',
    name: 'Horizontal Zip Duck Bag',
    family: 'duck-bag',
    imageUrl:
      'https://checkout.baggu.com/cdn/shop/files/71002610585129bd8a71cbb6d9d8387011b3ed8b-2048x2560_d62c3353-91d8-4679-8a37-3489fb0acab6_800x1000_crop_center.progressive.jpg?v=1784240934',
    imageAlt: 'Horizontal Zip Duck Bag in Natural Grid',
    bestFor: 'Work, school, and structured daily carry',
    capacitySummary: 'Medium-large capacity',
    carryStyle: 'Tote or shoulder carry',
    organizationSummary: 'Zippered structure for daily items',
    laptopFit: 'Potential laptop/work carry; confirm exact device fit before final content.',
    price: '$44',
    variantSummary: 'Multiple colors and prints',
    capacities: ['medium', 'large'],
    carryModes: ['tote', 'shoulder'],
    useCases: ['commute', 'daily'],
    structures: ['semiStructured'],
    priorities: ['organization', 'capacity'],
    flexibilityScore: 8,
    tradeoffs: ['More structured than nylon bags, but less packable.'],
  },
  {
    id: 'fanny-pack',
    name: 'Fanny Pack',
    family: 'fanny-pack',
    imageUrl:
      'https://cdn.shopify.com/s/files/1/0851/3262/files/d778c540f2aebf9ca108aa2f37b8f4ad89ffe96a-2048x2560_e109197f-793c-45e9-8201-6cf7b8f6ce12.jpg?v=1784240378',
    imageAlt: 'Fanny Pack in Black',
    bestFor: 'Compact hands-free essentials',
    capacitySummary: 'Small capacity for essentials',
    carryStyle: 'Hands-free waist or crossbody carry',
    organizationSummary: 'Compact pockets for small items',
    price: '$52',
    variantSummary: 'Multiple colors and prints',
    capacities: ['small'],
    carryModes: ['crossbody'],
    useCases: ['daily', 'evening', 'travel'],
    structures: ['semiStructured'],
    priorities: ['compact', 'handsFree', 'organization'],
    flexibilityScore: 7,
    tradeoffs: ['Best for essentials, not larger everyday loads.'],
  },
  {
    id: 'cloud-carry-on',
    name: 'Cloud Carry-On',
    family: 'cloud-bag',
    imageUrl:
      'https://checkout.baggu.com/cdn/shop/files/c72d0f9c3dd180c5f040dbbd9eca8071cb860da6-2048x2560_800x1000_crop_center.progressive.jpg?v=1782583604',
    imageAlt: 'Cloud Carry-On in Cherry',
    bestFor: 'Travel and oversized carry',
    capacitySummary: 'Oversized travel capacity',
    carryStyle: 'Shoulder carry',
    organizationSummary: 'Large travel compartment',
    price: '$78',
    variantSummary: 'Multiple colors and prints',
    capacities: ['oversized'],
    carryModes: ['shoulder'],
    useCases: ['travel'],
    structures: ['soft'],
    priorities: ['capacity'],
    flexibilityScore: 6,
    tradeoffs: ['Too large for most light daily carry.'],
  },
  {
    id: 'go-pouch-set',
    name: 'Go Pouch Set',
    family: 'pouch-set',
    imageUrl:
      'https://cdn.shopify.com/s/files/1/0851/3262/files/836bc54ede8cb3d6739200a1a387a9c3dc6e9689-2048x2560.jpg?v=1780320522',
    imageAlt: 'Go Pouch Set in Sandy Liang',
    bestFor: 'Organizing inside another bag',
    capacitySummary: 'Small-to-medium organization capacity',
    carryStyle: 'Packed inside another bag',
    organizationSummary: 'Multiple pouches for sorting essentials',
    price: '$40',
    variantSummary: 'Multiple colors and prints',
    capacities: ['small', 'medium'],
    carryModes: ['packable'],
    useCases: ['organization', 'travel', 'daily'],
    structures: ['soft'],
    priorities: ['organization', 'compact', 'giftable'],
    flexibilityScore: 7,
    tradeoffs: ['An organizer rather than a standalone bag for full carry.'],
  },
];
